server:
  port: 8080
  context-path: /
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/riverguides?useSSL=false
    username: riverguidesapi
    password: B2fa&hekuro7803!
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level: debug